name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - uses: actions/checkout@v3
      
      - name: tests
        run: ./gradlew test -x pmdMain -x pmdTest
